In [74]:
from sklearn.datasets import make_classification
import torch

In [75]:
# Step: 01: Creating a synthetic classification dataset using sklearn

X, y= make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [76]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [77]:
X.shape, X.dtype

((10, 2), dtype('float64'))

In [78]:
y, y.shape, y.dtype

(array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]), (10,), dtype('int64'))

In [79]:
from torch.utils.data import Dataset, DataLoader

In [80]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [81]:
dataset = CustomDataset(X, y)

In [82]:
len(dataset)

10

In [83]:
dataset[2]

(array([-2.8953973 ,  1.97686236]), np.int64(0))

In [84]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [85]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.7273, -1.1858],
        [-1.9629, -0.9923]], dtype=torch.float64)
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([1, 0])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([0, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.9382, -0.5430]], dtype=torch.float64)
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [ 1.0683, -0.9701]], dtype=torch.float64)
tensor([1, 1])
--------------------------------------------------

In [86]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import  LabelEncoder

In [87]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [88]:
df.shape

(569, 33)

In [89]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [90]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

**Train Test Split**

In [91]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

**Scaling**

In [92]:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [93]:
X_train

array([[-0.68277607,  0.16128567, -0.67728749, ..., -0.50238637,
         0.45049464,  0.28868489],
       [ 0.22347654, -0.60457003,  0.28458502, ...,  1.36241473,
         1.03970446,  1.22084782],
       [-0.45904496, -1.48244642, -0.52867552, ..., -1.33732613,
        -0.98910509, -0.76520754],
       ...,
       [ 0.92582232,  0.85627114,  0.79200048, ..., -0.48473599,
        -0.72170644, -1.04650141],
       [ 0.3565824 , -1.15552891,  0.44304972, ...,  1.92415729,
         2.72182856,  0.8348227 ],
       [-0.47037312, -0.97721027, -0.53770718, ..., -1.12674941,
        -0.02367158, -0.89954867]])

In [94]:
y_train

531    B
117    M
493    B
402    B
455    B
      ..
399    B
31     M
261    M
22     M
241    B
Name: diagnosis, Length: 455, dtype: object

**Label Encoding**

In [95]:
encoder  = LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.fit_transform(y_test)

In [96]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0])

**Numpy arrays to Pytorch tensors**

In [97]:
X_train_tensor= torch.from_numpy(X_train.astype(np.float32))
X_test_tensor= torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor= torch.from_numpy(y_test.astype(np.float32))

In [98]:
X_train_tensor.shape

torch.Size([455, 30])

In [99]:
from torch.utils.data import Dataset, DataLoader
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels =labels


  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [100]:
train_dataset= CustomDataset(X_train_tensor,y_train_tensor)
test_dataset= CustomDataset(X_test_tensor, y_test_tensor)

In [101]:
train_dataset[10]

(tensor([-0.6941,  2.2805, -0.6912, -0.6647, -0.2000, -0.3651, -0.2247, -0.7368,
         -0.0754, -0.1827, -0.3073,  2.1540, -0.3346, -0.3542,  0.8905, -0.0979,
          0.3119, -0.4201,  0.4490, -0.6492, -0.6344,  2.1010, -0.6175, -0.6014,
          0.3552, -0.3350,  0.0964, -0.6996, -0.0501, -0.6599]),
 tensor(0.))

In [102]:
train_data_loader= DataLoader(train_dataset, batch_size=32, shuffle=True, drop_last=False)
test_data_loader= DataLoader(test_dataset, batch_size=32, shuffle=True, drop_last=False)

**Defining Model**

In [103]:
import torch.nn as nn

In [104]:
class BreastCancerModel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid= nn.Sigmoid()


  def forward(self, features):
    out= self.linear(features)
    out= self.sigmoid(out)
    return out

**important parameters**

In [105]:
learning_rate= 0.1
epochs= 25

In [106]:
# creating model

model= BreastCancerModel(X_train_tensor.shape[1])
# define the optimizer
optimizer= torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function=nn.BCELoss()

**Training Pipline**

In [107]:
for epoch in range(epochs):
  for batch_features, batch_labels in train_data_loader:
    # forward pass
    y_pred= model(batch_features)
    # loss calculation

    loss= loss_function(y_pred, batch_labels.view(-1, 1))

    # clear gradients

    optimizer.zero_grad()
    # backward pass
    loss.backward()

    # parameters update

    optimizer.step()

  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.1429404765367508
Epoch: 2, Loss: 0.18339845538139343
Epoch: 3, Loss: 0.08560939133167267
Epoch: 4, Loss: 0.4758951961994171
Epoch: 5, Loss: 0.03404933586716652
Epoch: 6, Loss: 0.08282727003097534
Epoch: 7, Loss: 0.23309054970741272
Epoch: 8, Loss: 0.08916112035512924
Epoch: 9, Loss: 0.3405206799507141
Epoch: 10, Loss: 0.00986520480364561
Epoch: 11, Loss: 0.12786129117012024
Epoch: 12, Loss: 0.03244420140981674
Epoch: 13, Loss: 0.14578674733638763
Epoch: 14, Loss: 0.010123330168426037
Epoch: 15, Loss: 0.04645746573805809
Epoch: 16, Loss: 0.04383093863725662
Epoch: 17, Loss: 0.03215508162975311
Epoch: 18, Loss: 0.15233930945396423
Epoch: 19, Loss: 0.06227434054017067
Epoch: 20, Loss: 0.0019036101875826716
Epoch: 21, Loss: 0.028443897143006325
Epoch: 22, Loss: 0.030134690925478935
Epoch: 23, Loss: 0.11617381125688553
Epoch: 24, Loss: 0.06852920353412628
Epoch: 25, Loss: 0.10680096596479416

**Evaluation**

In [108]:
model.eval() # set the model to evaluation mode

accuracy_list= []
with torch.no_grad():
  for batch_features, batch_labels in test_data_loader:
    # forwad pass
    y_pred=model(batch_features)
    y_pred= (y_pred > 0.8).float() # convert probabilities into binary predictions

    # calculte accuracy
    batch_accuracy= (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


# calculating overall accuracy
overall_accuracy= sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy:{overall_accuracy:.4f}')

Accuracy:0.9253