In [99]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [100]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [101]:
df.shape

(569, 33)

In [102]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [103]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### Trian Test Split

In [104]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [105]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
210,20.580,22.14,134.70,1290.0,0.09090,0.13480,0.16400,0.09561,0.1765,0.05024,...,23.240,27.84,158.30,1656.0,0.11780,0.2920,0.38610,0.19200,0.2909,0.05865
284,12.890,15.70,84.08,516.6,0.07818,0.09580,0.11150,0.03390,0.1432,0.05935,...,13.900,19.69,92.12,595.6,0.09926,0.2317,0.33440,0.10170,0.1999,0.07127
312,12.760,13.37,82.29,504.1,0.08794,0.07948,0.04052,0.02548,0.1601,0.06140,...,14.190,16.40,92.04,618.8,0.11940,0.2208,0.17690,0.08411,0.2564,0.08253
283,16.240,18.77,108.80,805.1,0.10660,0.18020,0.19480,0.09052,0.1876,0.06684,...,18.550,25.09,126.90,1031.0,0.13650,0.4706,0.50260,0.17320,0.2770,0.10630
100,13.610,24.98,88.05,582.7,0.09488,0.08511,0.08625,0.04489,0.1609,0.05871,...,16.990,35.27,108.60,906.5,0.12650,0.1943,0.31690,0.11840,0.2651,0.07397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
539,7.691,25.44,48.34,170.4,0.08668,0.11990,0.09252,0.01364,0.2037,0.07751,...,8.678,31.89,54.49,223.6,0.15960,0.3064,0.33930,0.05000,0.2790,0.10660
293,11.850,17.46,75.54,432.7,0.08372,0.05642,0.02688,0.02280,0.1875,0.05715,...,13.060,25.75,84.35,517.8,0.13690,0.1758,0.13160,0.09140,0.3101,0.07007
118,15.780,22.91,105.70,782.6,0.11550,0.17520,0.21330,0.09479,0.2096,0.07331,...,20.190,30.50,130.30,1272.0,0.18550,0.4925,0.73560,0.20340,0.3274,0.12520
64,12.680,23.84,82.69,499.0,0.11220,0.12620,0.11280,0.06873,0.1905,0.06590,...,17.090,33.47,111.80,888.3,0.18510,0.4061,0.40240,0.17160,0.3383,0.10310
150,13.000,20.78,83.51,519.4,0.11350,0.07589,0.03136,0.02645,0.2540,0.06087,...,14.160,24.11,90.82,616.7,0.12970,0.1105,0.08112,0.06296,0.3196,0.06435

In [106]:
X_test

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
446,17.75,28.03,117.30,981.6,0.09997,0.13140,0.169800,0.08293,0.1713,0.05916,...,21.53,38.54,145.40,1437.0,0.14010,0.37620,0.63990,0.19700,0.2972,0.09075
323,20.34,21.51,135.90,1264.0,0.11700,0.18750,0.256500,0.15040,0.2569,0.06670,...,25.30,31.86,171.10,1938.0,0.15920,0.44920,0.53440,0.26850,0.5558,0.10240
179,12.81,13.06,81.29,508.8,0.08739,0.03774,0.009193,0.01330,0.1466,0.06133,...,13.63,16.15,86.70,570.7,0.11620,0.05445,0.02758,0.03990,0.1783,0.07319
349,11.95,14.96,77.23,426.7,0.11580,0.12060,0.011710,0.01787,0.2459,0.06581,...,12.81,17.72,83.09,496.2,0.12930,0.18850,0.03122,0.04766,0.3124,0.07590
475,12.83,15.73,82.89,506.9,0.09040,0.08269,0.058350,0.03078,0.1705,0.05913,...,14.09,19.35,93.22,605.8,0.13260,0.26100,0.34760,0.09783,0.3006,0.07802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.351400,0.15200,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,0.16500,0.86810,0.93870,0.26500,0.4087,0.12400
384,13.28,13.72,85.79,541.8,0.08363,0.08575,0.050770,0.02864,0.1617,0.05594,...,14.24,17.37,96.59,623.7,0.11660,0.26850,0.28660,0.09173,0.2736,0.07320
529,12.07,13.44,77.83,445.2,0.11000,0.09009,0.037810,0.02798,0.1657,0.06608,...,13.45,15.77,86.92,549.9,0.15210,0.16320,0.16220,0.07393,0.2781,0.08052
281,11.74,14.02,74.24,427.3,0.07813,0.04340,0.022450,0.02763,0.2101,0.06113,...,13.31,18.26,84.70,533.7,0.10360,0.08500,0.06735,0.08290,0.3101,0.06688
443,10.57,18.32,66.82,340.9,0.08142,0.04462,0.019930,0.01111,0.2372,0.05768,...,10.94,23.31,69.35,366.3,0.09794,0.06542,0.03986,0.02222,0.2699,0.06736

In [107]:
y_train

210    M
284    B
312    B
283    M
100    M
      ..
539    B
293    B
118    M
64     M
150    B
Name: diagnosis, Length: 455, dtype: object

In [108]:
y_test

446    M
323    M
179    B
349    B
475    B
      ..
567    M
384    B
529    B
281    B
443    B
Name: diagnosis, Length: 114, dtype: object

### Scaling

In [109]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [110]:
X_train

array([[ 1.79935941,  0.64223133,  1.73302855, ...,  1.16204202,
         0.02009201, -1.38966236],
       [-0.36226471, -0.84610414, -0.33681981, ..., -0.21157516,
        -1.50690834, -0.70657153],
       [-0.39880712, -1.38458576, -0.41001278, ..., -0.47914909,
        -0.5588257 , -0.09709428],
       ...,
       [ 0.45010118,  0.82018448,  0.54722052, ...,  1.33545549,
         0.63257018,  2.21253218],
       [-0.42129476,  1.03511492, -0.39365681, ...,  0.85172319,
         0.81547462,  1.0163113 ],
       [-0.33134421,  0.32792446, -0.36012707, ..., -0.8008767 ,
         0.50168443, -1.0811348 ]])

### Label Encoding

In [111]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test= encoder.fit_transform(y_test)

In [112]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0])

### Numpay arrays to PyTorch tensors

In [113]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor =torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [114]:
X_train_tensor.shape

torch.Size([455, 30])

In [115]:
X_train_tensor

tensor([[ 1.7994,  0.6422,  1.7330,  ...,  1.1620,  0.0201, -1.3897],
        [-0.3623, -0.8461, -0.3368,  ..., -0.2116, -1.5069, -0.7066],
        [-0.3988, -1.3846, -0.4100,  ..., -0.4791, -0.5588, -0.0971],
        ...,
        [ 0.4501,  0.8202,  0.5472,  ...,  1.3355,  0.6326,  2.2125],
        [-0.4213,  1.0351, -0.3937,  ...,  0.8517,  0.8155,  1.0163],
        [-0.3313,  0.3279, -0.3601,  ..., -0.8009,  0.5017, -1.0811]],
       dtype=torch.float64)

In [116]:
y_train_tensor.shape

torch.Size([455])

In [117]:
y_train_tensor

tensor([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0])

### Deifine Model

In [118]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1 , dtype=torch.float64, requires_grad=True)
    self.bias= torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # calculate loss
    loss  = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [119]:
X_train_tensor.dtype

torch.float64

### Important Parameters

In [120]:
learning_rate = 0.1
epochs = 50

Training Pipeline

In [121]:
# Create Model
model = MySimpleNN(X_train_tensor)

# define loop

for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)
  # calculate losss
  loss = model.loss_function(y_pred, y_train_tensor)
  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients

  model.weights.grad.zero_()
  model.bias.grad.zero_()



  print(f'Epoch:  {epoch+ 1}, Loss: {loss.item()}')

Epoch:  1, Loss: 3.835248382917436
Epoch:  2, Loss: 3.7066080438119187
Epoch:  3, Loss: 3.57317752825293
Epoch:  4, Loss: 3.4375181799513155
Epoch:  5, Loss: 3.294332209771813
Epoch:  6, Loss: 3.1417234054899716
Epoch:  7, Loss: 2.9874722955283373
Epoch:  8, Loss: 2.832937875659677
Epoch:  9, Loss: 2.6667243458895826
Epoch:  10, Loss: 2.5034050628668667
Epoch:  11, Loss: 2.3385844607470503
Epoch:  12, Loss: 2.1762313950433994
Epoch:  13, Loss: 2.0118584835829525
Epoch:  14, Loss: 1.852505894501177
Epoch:  15, Loss: 1.6982662423699304
Epoch:  16, Loss: 1.5531500618696614
Epoch:  17, Loss: 1.4208450794610263
Epoch:  18, Loss: 1.302748691711041
Epoch:  19, Loss: 1.1998217603956784
Epoch:  20, Loss: 1.112409315425775
Epoch:  21, Loss: 1.0400899129929284
Epoch:  22, Loss: 0.981606976294679
Epoch:  23, Loss: 0.9350042773176557
Epoch:  24, Loss: 0.8980026319749601
Epoch:  25, Loss: 0.8684375034872411
Epoch:  26, Loss: 0.8445276200105285
Epoch:  27, Loss: 0.8249273694008483
Epoch:  28, Loss: 0.8086592686045802
Epoch:  29, Loss: 0.7950180354855966
Epoch:  30, Loss: 0.7834873621355251
Epoch:  31, Loss: 0.7736788511750854
Epoch:  32, Loss: 0.7652907399470126
Epoch:  33, Loss: 0.7580814239916188
Epoch:  34, Loss: 0.7518531273834365
Epoch:  35, Loss: 0.7464419966930798
Epoch:  36, Loss: 0.7417118656528631
Epoch:  37, Loss: 0.7375498754488353
Epoch:  38, Loss: 0.7338629484364629
Epoch:  39, Loss: 0.7305746891754811
Epoch:  40, Loss: 0.7276226005311661
Epoch:  41, Loss: 0.7249556204980301
Epoch:  42, Loss: 0.7225319997061452
Epoch:  43, Loss: 0.7203175183738405
Epoch:  44, Loss: 0.7182840186491138
Epoch:  45, Loss: 0.7164082144764794
Epoch:  46, Loss: 0.7146707363599886
Epoch:  47, Loss: 0.7130553696520681
Epoch:  48, Loss: 0.7115484493762044
Epoch:  49, Loss: 0.7101383801069734
Epoch:  50, Loss: 0.7088152549563682

In [122]:
model.weights, model.weights.shape, model.weights.dtype

(tensor([[ 0.4283],
         [-0.1714],
         [ 0.2133],
         [-0.2934],
         [-0.4452],
         [-0.2733],
         [ 0.0726],
         [ 0.2018],
         [ 0.1929],
         [ 0.2374],
         [-0.1942],
         [-0.0751],
         [-0.3178],
         [ 0.1988],
         [ 0.2554],
         [ 0.0562],
         [-0.3129],
         [ 0.0408],
         [ 0.1626],
         [ 0.3032],
         [ 0.1623],
         [ 0.3114],
         [-0.2341],
         [ 0.4416],
         [ 0.3543],
         [ 0.3451],
         [-0.2540],
         [-0.5117],
         [-0.2836],
         [ 0.0294]], dtype=torch.float64, requires_grad=True),
 torch.Size([30, 1]),
 torch.float64)

In [123]:
model.bias, model.bias.shape

(tensor([-0.2702], dtype=torch.float64, requires_grad=True), torch.Size([1]))

In [124]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.6809787750244141